# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69fb167e25c65c80b2b52e495fd89e8f9570c6437b7e133802720c101f4fed6e318953f1b4dd136452ba9bcc31bdc780c17a59db57d95c016578b2167240ed66

test:
  secret_key_base: 93cc4e3b016041311b807f34ee4ebeb72fc802fadfd6a3dbe5d9884feb92603fce1380194af9f8be31a1f5ffcda4ffdd6f3881535819a8de40837fe0b134d0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
